### ISSUE TITLE
switch `elevation` property to `elevation-dp`?

### ISSUE THREAD

**Issue by morethanreal** [PolymerElements/paper-material#4]
Since the spec specifies elevation in dp, switch to that api?

**Comment by notwaldorf** [comment]
apply label: api-feedback

**Comment by bendavis78** [comment]
+1

[The MD spec page on elevation](https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-) has a table of the appropriate dp elevation for various components. Putting elevation in terms of dp rather than an arbitrary 5 options allows a closer adherence to the spec.

**Comment by AndreasGalster** [comment]
I agree. Looking at the specs and using Polymer, it's very unclear how to implement the elevation of objects properly. In Material Design there are about 24 steps of elevation, in Polymer there are only 5.

**Comment by notwaldorf** [comment]
We're not going to change the API at this point, since it's a breaking change; also this element is a bit of an anti pattern from a performance perspective (it just applies a shadow) and should be revisited.
